security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/(admin)
            anonymous: true
            lazy: true
            provider: app_user_provider
            logout:
                path: admin_logout
            guard:
                authenticators:
                    - App\Security\Authenticator\AdminLoginFormAuthenticator
            entry_point: App\Security\EntryPoint\AdminAuthenticationEntryPoint
        site:
            anonymous: true
            lazy: true
            provider: app_user_provider
            logout:
                path: site_logout
            guard:
                authenticators:
                    - App\Security\Authenticator\SiteLoginFormAuthenticator
            entry_point: App\Security\EntryPoint\SiteAuthenticationEntryPoint
    access_control:
         - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin, roles: ROLE_ADMIN }
